# Generated by Django 3.2 on 2021-04-30 08:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=accounts.models.upload_to, verbose_name='Image'),
        ),
    ]
