# Generated by Django 3.2.3 on 2021-05-14 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210508_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_accounts_user_friends_+', through='accounts.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
