# Generated by Django 3.2.3 on 2021-05-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
    ]
