# Generated by Django 3.2.3 on 2021-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210516_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
